// <auto-generated />
using System;
using AccountingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309182525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingApp.Models.AccountBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GLAccountId");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("AccountingApp.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid?>("ControlAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlAccountId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AccountingApp.Models.DaybookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedDaybookEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LinkedDaybookEntryId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("SupplierId");

                    b.ToTable("DaybookEntries");
                });

            modelBuilder.Entity("AccountingApp.Models.GLAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("GLAccounts");
                });

            modelBuilder.Entity("AccountingApp.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DaybookEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("NarrationLine")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DaybookEntryId");

                    b.HasIndex("GLAccountId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("AccountingApp.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultVatAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("VatFullRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatReducedRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DefaultVatAccountId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("AccountingApp.Models.OrganisationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("OrganisationInvitations");
                });

            modelBuilder.Entity("AccountingApp.Models.OrganisationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganisationMembers");
                });

            modelBuilder.Entity("AccountingApp.Models.ProductService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DefaultSalePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("VatTreatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AccountingApp.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid?>("ControlAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlAccountId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AccountingApp.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MicrosoftId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("GoogleId IS NOT NULL");

                    b.HasIndex("MicrosoftId")
                        .IsUnique()
                        .HasFilter("MicrosoftId IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AccountingApp.Models.AccountBalance", b =>
                {
                    b.HasOne("AccountingApp.Models.GLAccount", "GLAccount")
                        .WithMany()
                        .HasForeignKey("GLAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GLAccount");
                });

            modelBuilder.Entity("AccountingApp.Models.Customer", b =>
                {
                    b.HasOne("AccountingApp.Models.GLAccount", "ControlAccount")
                        .WithMany("Customers")
                        .HasForeignKey("ControlAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("Customers")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlAccount");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("AccountingApp.Models.DaybookEntry", b =>
                {
                    b.HasOne("AccountingApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingApp.Models.DaybookEntry", "LinkedDaybookEntry")
                        .WithMany()
                        .HasForeignKey("LinkedDaybookEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("DaybookEntries")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingApp.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("LinkedDaybookEntry");

                    b.Navigation("Organisation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AccountingApp.Models.GLAccount", b =>
                {
                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("GLAccounts")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("AccountingApp.Models.JournalEntry", b =>
                {
                    b.HasOne("AccountingApp.Models.DaybookEntry", "DaybookEntry")
                        .WithMany("JournalEntries")
                        .HasForeignKey("DaybookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingApp.Models.GLAccount", "GLAccount")
                        .WithMany("JournalEntries")
                        .HasForeignKey("GLAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DaybookEntry");

                    b.Navigation("GLAccount");
                });

            modelBuilder.Entity("AccountingApp.Models.Organisation", b =>
                {
                    b.HasOne("AccountingApp.Models.GLAccount", "DefaultVatAccount")
                        .WithMany()
                        .HasForeignKey("DefaultVatAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DefaultVatAccount");
                });

            modelBuilder.Entity("AccountingApp.Models.OrganisationInvitation", b =>
                {
                    b.HasOne("AccountingApp.Models.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("AccountingApp.Models.OrganisationMember", b =>
                {
                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("Members")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingApp.Models.User", "User")
                        .WithMany("OrganisationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountingApp.Models.ProductService", b =>
                {
                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("Products")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("AccountingApp.Models.Supplier", b =>
                {
                    b.HasOne("AccountingApp.Models.GLAccount", "ControlAccount")
                        .WithMany("Suppliers")
                        .HasForeignKey("ControlAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingApp.Models.Organisation", "Organisation")
                        .WithMany("Suppliers")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlAccount");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("AccountingApp.Models.DaybookEntry", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("AccountingApp.Models.GLAccount", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("JournalEntries");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("AccountingApp.Models.Organisation", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("DaybookEntries");

                    b.Navigation("GLAccounts");

                    b.Navigation("Members");

                    b.Navigation("Products");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("AccountingApp.Models.User", b =>
                {
                    b.Navigation("OrganisationMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
